# Generated by Django 4.2.23 on 2025-11-01 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans_app', '0002_new_planning_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacion',
            options={},
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='version',
        ),
        migrations.CreateModel(
            name='PlanificacionAsistenteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('completada', 'Completada'), ('validada', 'Validada con IA')], default='borrador', max_length=20)),
                ('datos_generales', models.TextField(blank=True, help_text='Carrera, asignatura, semestre, etc.')),
                ('diagnostico_estudiantes', models.TextField(blank=True, help_text='Conocimientos y brechas de estudiantes en IAGen')),
                ('habilidades_propias', models.TextField(blank=True, help_text='Autoevaluación docente')),
                ('objetivo_actividad', models.TextField(blank=True, help_text='Objetivo claro y medible')),
                ('contexto_temporalidad', models.TextField(blank=True, help_text='Contexto y temporalidad de la experiencia')),
                ('herramientas_iagen', models.TextField(blank=True, help_text='Herramientas IAGen y escenarios')),
                ('metodologia_estrategia', models.TextField(blank=True, help_text='Metodología o estrategia didáctica')),
                ('indicadores_evaluacion', models.TextField(blank=True, help_text='Indicadores de evaluación')),
                ('inicio_clase', models.TextField(blank=True, help_text='Inicio de la clase')),
                ('desarrollo_clase', models.TextField(blank=True, help_text='Desarrollo de la clase')),
                ('cierre_clase', models.TextField(blank=True, help_text='Cierre de la clase')),
                ('pilares_eticos', models.TextField(blank=True, help_text='Aspectos éticos y de integridad académica')),
                ('registro_implementacion', models.TextField(blank=True, help_text='Registro de la implementación')),
                ('evaluacion_experiencia', models.TextField(blank=True, help_text='Evaluación de la experiencia')),
                ('acciones_posteriores', models.TextField(blank=True, help_text='Acciones de consolidación')),
                ('facilitadores_obstaculos', models.TextField(blank=True, help_text='Facilitadores y obstáculos')),
                ('reflexion_practica', models.TextField(blank=True, help_text='Reflexión sobre la práctica')),
                ('feedback_ia', models.JSONField(blank=True, default=list, help_text='Historial de validaciones con IA')),
                ('capitulos_validados', models.JSONField(blank=True, default=list, help_text='Capítulos usados en validación')),
                ('ultima_validacion', models.TextField(blank=True, help_text='Último feedback de IA')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planificación con Asistente IA',
                'verbose_name_plural': 'Planificaciones con Asistente IA',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
