name: Build and deploy Django app to Azure Web App - ia-backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Checkout en la raíz (Proyecto-main/Proyecto-main/)
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        # CLAVE: Ejecutamos el comando *dentro* de la carpeta 'backend'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
        working-directory: backend # <--- ¡Nuevo uso de working-directory!

      - name: Run migrations
        run: |
          # Ahora solo se necesita 'manage.py' ya que estamos en 'backend/'
          python manage.py migrate --noinput
        working-directory: backend

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput
        working-directory: backend

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          # Subimos la carpeta 'backend/' completa.
          # Nota: Esta ruta es relativa a la raíz del repositorio, no al working-directory.
          path: backend/ 

  # ---
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: . 

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ia-backend"
          slot-name: "Production"
          package: .
