name: Build and deploy Django app to Azure Web App - ia-backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # --- 1. Install Dependencies ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
        working-directory: backend 

      # --- 2. Run Migrations (Fixes ModuleNotFoundError) ---
      - name: Run migrations
        run: |
          # CLAVE: Agrega la carpeta 'backend/' (representada por '.') al PYTHONPATH.
          PYTHONPATH=$PYTHONPATH:. DJANGO_SETTINGS_MODULE=src.config.settings django-admin migrate --noinput
        working-directory: backend

      # --- 3. Collect Static Files (Fixes ModuleNotFoundError) ---
      - name: Collect static files
        run: |
          PYTHONPATH=$PYTHONPATH:. DJANGO_SETTINGS_MODULE=src.config.settings django-admin collectstatic --noinput
        working-directory: backend

      # --- 4. Upload Artifact (Fixes YAML Syntax Error) ---
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          # CLAVE: Usa comillas simples en el path para evitar errores de sintaxis YAML.
          # Esto apunta a la carpeta 'backend' dentro del workspace.
          path: '${{ github.workspace }}/backend/' 
          
---

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: . 

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ia-backend"
          slot-name: "Production"
          package: .
