name: Build and deploy Django app to Azure Web App - ia-backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # --- Pasos que usan working-directory ---

      - name: Install dependencies
        # Entra en 'backend' para ejecutar el comando.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
        working-directory: backend 

      - name: Run migrations
        # Entra en 'backend' para ejecutar el comando.
        run: |
          python manage.py migrate --noinput
        working-directory: backend

      - name: Collect static files
        # Entra en 'backend' para ejecutar el comando.
        run: |
          python manage.py collectstatic --noinput
        working-directory: backend

      # --- Paso de Upload Crítico ---

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          # CLAVE: Usamos la ruta absoluta del Workspace de GitHub
          # para apuntar a la carpeta 'backend', evitando el error de ruta.
          # Esto resuelve el problema de la doble anidación.
          path: ${{ github.workspace }}/backend/
          
  # ---
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: . 

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ia-backend"
          slot-name: "Production"
          package: .
