name: Build and deploy Django app to Azure Web App - ia-backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # ELIMINAMOS 'defaults' para evitar conflictos con la ruta de checkout.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # El código se clona en la raíz del runner (e.g., /home/runner/work/Proyecto-main/Proyecto-main/)

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # IMPORTANTE: Usar la ruta explícita a requirements.txt
          pip install -r backend/requirements.txt 

      - name: Run migrations
        run: |
          # Usamos la ruta explícita al 'manage.py'
          python backend/manage.py migrate --noinput 

      - name: Collect static files
        run: |
          # Usamos la ruta explícita al 'manage.py'
          python backend/manage.py collectstatic --noinput 

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          # CRÍTICO: Solo subimos la carpeta 'backend' como artefacto
          path: backend/
          # Usamos 'backend/' para que el contenido de backend (incluyendo manage.py) 
          # sea la raíz del paquete de despliegue.
          
# ---

### Job `deploy`: Despliegue directo del artefacto

El job de despliegue queda bien, ya que descarga la carpeta `backend` y la despliega:

```yaml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: . # Descarga el contenido de 'backend/' a la raíz del directorio de este job

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ia-backend"
          slot-name: "Production"
          package: . # Despliega el contenido descargado (que es tu app Django)
