name: Build and deploy Django app to Azure Web App - ia-backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # Se eliminó 'defaults.run.working-directory: backend' para usar rutas explícitas.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Ruta explícita: 'backend/requirements.txt'
          pip install -r backend/requirements.txt 

      - name: Run migrations
        run: |
          # Ruta explícita: 'backend/manage.py'
          python backend/manage.py migrate --noinput 

      - name: Collect static files
        run: |
          # Ruta explícita: 'backend/manage.py'
          python backend/manage.py collectstatic --noinput 

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          # CRÍTICO: Subir solo el contenido de la carpeta 'backend'
          # Esto asegura que manage.py esté en la raíz del paquete de despliegue.
          path: backend/
          # Excluir el entorno virtual si se crea en la raíz
          # path: |
          #   backend/
          #   !venv/ 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: . 
          # Esto descarga el contenido de 'backend/' a la raíz de este job.

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ia-backend"
          slot-name: "Production"
          package: . 
          # Despliega el contenido de la carpeta, donde Azure espera encontrar tu app.
