name: Build and deploy Django app to Azure Web App - ia-backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # --- Instalación de dependencias ---

      - name: Install dependencies
        # Entra en 'backend' para encontrar requirements.txt.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
        working-directory: backend 

      # --- Ejecución de Comandos de Django (CORREGIDO) ---

      - name: Run migrations
        # CLAVE: Usa DJANGO_SETTINGS_MODULE y django-admin.
        # Asumiendo que tu archivo de configuración está en backend/src/config/settings.py
        run: |
          DJANGO_SETTINGS_MODULE=src.config.settings django-admin migrate --noinput
        working-directory: backend

      - name: Collect static files
        # CLAVE: Usa DJANGO_SETTINGS_MODULE y django-admin.
        run: |
          DJANGO_SETTINGS_MODULE=src.config.settings django-admin collectstatic --noinput
        working-directory: backend

      # --- Subida de Artefacto ---

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          # Usar la ruta absoluta al backend es lo más seguro.
          path: ${{ github.workspace }}/backend/
          
  # ---
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # ... (El job deploy no necesita cambios ya que el artefacto es el mismo)
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: . 

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ia-backend"
          slot-name: "Production"
          package: .
