name: Build and deploy Django app to Azure Web App - ia-backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code to specific directory
        uses: actions/checkout@v4
        with:
          # CLAVE: Clonamos el repo en la carpeta 'app-source'
          path: app-source 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Usamos el nuevo path: 'app-source/backend/requirements.txt'
          pip install -r app-source/backend/requirements.txt 
          
      - name: Run migrations
        run: |
          # Usamos el nuevo path: 'app-source/backend/manage.py'
          python app-source/backend/manage.py migrate --noinput 

      - name: Collect static files
        run: |
          # Usamos el nuevo path: 'app-source/backend/manage.py'
          python app-source/backend/manage.py collectstatic --noinput 

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          # CRÍTICO: Subir solo la carpeta de la aplicación desde el nuevo path
          path: app-source/backend/
          
  # ---
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: . 
          
      # ... (Pasos de Azure Login y Deploy) ...
      
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ia-backend"
          slot-name: "Production"
          package: .
