name: Build and deploy Django app to Azure Web App - ia-backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # --- 1. Install Dependencies ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
        working-directory: backend 

      # --- 2. Collect Static Files ---
      - name: Collect static files
        run: |
          PYTHONPATH=$PYTHONPATH:. DJANGO_SETTINGS_MODULE=config.settings django-admin collectstatic --noinput
        working-directory: backend/src 

      # --- 3. Upload Artifact ---
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: '${{ github.workspace }}/backend/' 
          
# ==================================
# ESTE ES EL JOB CRÍTICO QUE DEBE EXISTIR:
# ==================================
  deploy:
    runs-on: ubuntu-latest
    needs: build # Se ejecuta SÓLO si 'build' tuvo éxito.
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: . 

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ia-backend"
          slot-name: "Production"
          package: .
